trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build images with docker-compose
  jobs:
  - job: Build
    displayName: Build using docker-compose
    pool:
      name: vm-linux  # Seu agente self-hosted na VM
    steps:
    - checkout: self

    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'DevOps Service Connection'
        KeyVaultName: 'DocBrasilKeyVault'
        SecretsFilter: 'AssociateDbPassword,AuthDbPassword,AssociateAuthKey,AssociateKey,AzureBlobContainerSecretKey,AzureSecretKey'
      name: FetchSecrets
      runAsPreJob: true

    - script: |
        cd frontend/doc-brasil
        /usr/bin/npm ci
        /usr/bin/ng build --configuration=production
      displayName: 'Build frontend Angular'

    - script: |
        echo "Gerando .env.prod..."
        echo "MYSQL_ASSOCIADOS_PASSWORD=$(AuthDbPassword)" > .env.prod
        echo "MYSQL_ASSOCIADOS_AUTH_PASSWORD=$(AssociateDbPassword)" >> .env.prod
        echo "ConnectionStrings__MySqlConnection=Server=associados-db;Database=associadosdb;User=root;Password=$(AuthDbPassword)" >> .env.prod
        echo "ConnectionStrings__MySqlAuthConnection=Server=associadosAuth-db;Database=associadosAuthdb;User=docBrasilProdAuth;Password=$(AssociateDbPassword)" >> .env.prod
      displayName: 'Gerar arquivo .env.prod'
      workingDirectory: $(Build.SourcesDirectory)

    - script: |
        echo "Iniciando containers com docker-compose..."
        export PATH=$PATH:/usr/bin
        /usr/bin/sudo docker compose --env-file .env.prod -f docker-compose.yml -f docker-compose-prod.yml down --remove-orphans
        /usr/bin/sudo docker compose --env-file .env.prod -f docker-compose.yml -f docker-compose-prod.yml up -d --build
      displayName: 'Subir containers com docker-compose'
      workingDirectory: $(Build.SourcesDirectory)
