# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build images with docker-compose
  jobs:
  - job: Build
    displayName: Build using docker-compose
    pool:
      name: vm-linux
    steps:
    - checkout: self

    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'DevOps Service Connection'
        KeyVaultName: 'DocBrasilKeyVault'
        SecretsFilter: 'AssociateDbPassword,AuthDbPassword,AssociateAuthKey,AssociateKey,AzureBlobContainerSecretKey,AzureSecretKey'
        RunAsPreJob: true

    - script: |
        echo "Remapeando variáveis..."
        export MYSQL_ASSOCIADOS_PASSWORD=$(AuthDbPassword)
        export MYSQL_ASSOCIADOS_AUTH_PASSWORD=$(AssociateDbPassword)
        echo "MYSQL_ASSOCIADOS_PASSWORD = $MYSQL_ASSOCIADOS_PASSWORD"
        echo "MYSQL_ASSOCIADOS_AUTH_PASSWORD = $MYSQL_ASSOCIADOS_AUTH_PASSWORD"
        export PATH=$PATH:/usr/bin
        /usr/bin/docker-compose -f docker-compose.yml -f docker-compose-prod.yml build --no-cache
      workingDirectory: $(Build.SourcesDirectory)
      displayName: Build containers with docker-compose
