server {
    listen 80;
    listen 443 ssl;
    server_name appdocdobrasil.com.br;

    ssl_certificate /etc/letsencrypt/live/appdocdobrasil.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/appdocdobrasil.com.br/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Servir frontend
    location / {
        proxy_pass http://associados_frontend:80;root /var/www/html;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy para API Gateway
    location /auth/ {
        proxy_pass http://associados_api-gateway:8080/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /associados/ {
        proxy_pass http://associados_api-gateway:8080/associados/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
