name: Deploy na VM Azure

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node e Angular CLI
        run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install -g @angular/cli

      - name: Instalar dependências e buildar o frontend
        working-directory: ./frontend/doc-brasil
        run: |
          npm ci
          ng build --configuration=production

      - name: Mover pasta dist para project-root/frontend
        run: |
          mkdir -p frontend
          if [ -d "frontend/doc-brasil/dist/doc-brasil" ]; then
            cp -r frontend/doc-brasil/dist/doc-brasil/* frontend/
          else
            echo "❌ Pasta 'dist/doc-brasil' não encontrada."
            exit 1
          fi

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Enviar arquivos para a VM
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" ./ azureuser@${{ secrets.VM_HOST }}:/home/azureuser/associados-app

      - name: Reconstruir containers com Docker Compose
        run: |
          ssh -i ~/.ssh/id_rsa azureuser@${{ secrets.VM_HOST }} << 'EOF'
            cd /home/azureuser/associados-app
            docker compose down
            docker-compose build --no-cache
            docker compose up -d
          EOF
